"""
HexStrike AI-PULSE — MCP server instructions (Couche 2).

Injected as FastMCP(instructions=...) so MCP clients receive it
as part of the initialization handshake. The instructions are
visible to Claude Code (terminal) but silently dropped by
Claude Desktop (known bug, still open as of May 2026).
"""

INSTRUCTIONS = (
    "You are connected to HexStrike AI-PULSE, a security reconnaissance and analysis framework.\n"
    "Note: these instructions are silently dropped by Claude Desktop (known Anthropic bug, still open as of June 2026)."
    "They are visible in Claude Code and compatible MCP clients.\n"
    "\n"
    "# Entry Points\n"
    "- `scan(target, intensity, objective)` — unified entry: quick (nmap+whatweb), medium (+nuclei+nikto), full (+gobuster). Auto-detects scope if target omitted.\n"
    "- `scan_background(target, intensity, objective)` — async scan for >30s operations. Returns immediately. Background task runs independently.\n"
    "- `get_live_dashboard(target)` — all dashboard panels in one call (~100ms).\n"
    "- Individual tools: `get_overview()`, `get_scope()`, `get_surface(target)`, `get_findings(target)`, `get_plan(target)`, `get_active_tools()`, `get_history(target)`.\n"
    "- `http_request(url, method, ...)` — generic HTTP client (wraps curl). Returns status_code, headers, body, cookies. Binary responses: check `body_hex` field.\n"
    "- `raw_tcp(host, port, payload_hex)` — raw TCP socket primitive for protocol testing.\n"
    "- `run_security_tool(tool_name, parameters)` — universal executor for all 130+ tools.\n"
    "- `run_async_tool(tool, target, params)` — launches background scan, returns scan_id immediately. Poll with `get_scan_status(scan_id)`.\n"
    "- `search_tools(pattern)` — search available tools by regex. `call_tool(name, arguments)` — execute a discovered tool by name.\n"
    "\n"
    "# Tool Lifecycle\n"
    "- `tool_status(tool_name)` — check if a tool binary is installed. Returns path, version, and install hint.\n"
    "- `install_tool(tool_name)` — auto-install missing tools via apt/pip/gem. Supports 50+ tools.\n"
    "\n"
    "# Workflow Order\n"
    "1. `get_overview()` — check server health and system status.\n"
    "2. `get_scope()` or `scan()` — set or detect active target.\n"
    "3. `get_surface(target)` — ports, services, tech stack, risk level.\n"
    "4. `get_findings(target)` — vulnerabilities from nuclei/nikto.\n"
    "5. `get_plan(target, objective)` — attack chain with success probability and ETA.\n"
    "\n"
    "Use `get_live_dashboard(target)` INSTEAD of calling individual tools when you need the full picture.\n"
    "\n"
    "# Workflow Prompts (MCP native)\n"
    "Available via ctx.get_prompt() for multi-tool attack chains:\n"
    "- `bug_bounty_recon(target)` — full bug bounty workflow (WAF → subdomain → ports → dir → vuln).\n"
    "- `wifi_attack_chain(interface, bssid, channel)` — WPA handshake capture and crack.\n"
    "- `ctf_web_challenge(url)` — CTF web enumeration and exploitation.\n"
    "- `ctf_challenge(name, category, ...)` — universal CTF for all 7 categories.\n"
    "- `smb_lateral_movement(target)` — SMB enum → null session → EternalBlue check.\n"
    "- `cloud_security_audit(provider, profile)` — Prowler → Trivy → kube-hunter.\n"
    "\n"
    "# MCP Resources\n"
    "- `health://server` — server status and version.\n"
    "- `telemetry://summary` — telemetry aggregated counts and top tools.\n"
    "- `telemetry://recent` — recent telemetry events (last 100).\n"
    "- `telemetry://tools/{tool_name}` — per-tool telemetry stats.\n"
    "- `targets://` — all scanned targets.\n"
    "- `target://{target}` — target profile (ports, vulns, tools used).\n"
    "- `target://{target}/findings` — vulnerabilities per target.\n"
    "- `target://{target}/sessions` — scan sessions per target.\n"
    "- `scan://{target}/latest` — latest scan results per target.\n"
    "- `scan://{target}/{tool_name}` — latest scan result for a specific tool on target.\n"
    "- `scan://cache` — cached scan index (all cached tools/targets).\n"
    "- `metrics://tools` — tool effectiveness statistics.\n"
    "- `errors://statistics` — error distribution.\n"
    "- `skill://{category}/SKILL.md` — per-category skill guidance (nmap-recon, web-recon, web-vuln, exploitation, etc.).\n"
    "\n"
    "# Tool Naming\n"
    "- Tool names use underscores (e.g., `nmap_advanced`, `airmon_ng`, `kube_hunter`).\n"
    "- The `run_security_tool(tool_name, parameters)` function accepts any tool name.\n"
    "- Typed wrappers exist for common tools: `nmap(target, ports, scan_type)`, `whatweb(target)`, `sqlmap(url, ...)`, etc.\n"
    "- The `_profile` parameter controls stealth: `normal` (default), `stealth`, `aggressive`.\n"
    "- ParameterOptimizer auto-tunes tool flags based on WAF detection, rate limits, and target profile.\n"
    "\n"
    "# Caching\n"
    "- Scan results are cached automatically. Repeated calls with the same tool+target return instantly.\n"
    "- Cache is adaptive: high-hit tools get longer TTL (up to 2h), low-hit tools get shorter (min 5min).\n"
    "- To force a fresh scan, pass an explicit target not seen recently.\n"
    "\n"
    "# Destructive Tools\n"
    "The following tools require explicit user confirmation before execution:\n"
    "Metasploit, aireplay-ng, responder, mitm6, mdk4.\n"
    "The server will prompt for confirmation automatically — do not bypass it.\n"
    "\n"
    "# Skills (per-category guidance)\n"
    "Each tool category has a SKILL.md with workflow guidance. Use `get_tool_skill(tool_name)` to view the relevant skill document for deep guidance on specific tool categories.\n"
)
