#!/usr/bin/env python3
"""
Shared tool route definitions — single source of truth for all tool→binary mappings.

Each entry is (module_path, exec_func_name, binary_name).
Used by hexstrike.py (lazy import via importlib) and server_setup.py (eager import).
"""

TOOL_ROUTES = {
    # wifi
    "airmon_ng":         ("mcp_core.wifi_direct", "wifi_exec", "airmon-ng"),
    "airodump_ng":       ("mcp_core.wifi_direct", "wifi_exec", "airodump-ng"),
    "aireplay_ng":       ("mcp_core.wifi_direct", "wifi_exec", "aireplay-ng"),
    "aircrack_ng":       ("mcp_core.wifi_direct", "wifi_exec", "aircrack-ng"),
    "hcxdumptool":       ("mcp_core.wifi_direct", "wifi_exec", "hcxdumptool"),
    "hcxpcapngtool":     ("mcp_core.wifi_direct", "wifi_exec", "hcxpcapngtool"),
    "eaphammer":         ("mcp_core.wifi_direct", "wifi_exec", "eaphammer"),
    "wifite":            ("mcp_core.wifi_direct", "wifi_exec", "wifite2"),
    "airbase_ng":        ("mcp_core.wifi_direct", "wifi_exec", "airbase-ng"),
    "airdecap_ng":       ("mcp_core.wifi_direct", "wifi_exec", "airdecap-ng"),
    "bettercap":         ("mcp_core.wifi_direct", "wifi_exec", "bettercap_wifi"),
    "tcpdump":           ("mcp_core.wifi_direct", "wifi_exec", "tcpdump"),
    "tshark":            ("mcp_core.wifi_direct", "wifi_exec", "tshark"),
    "mdk4":              ("mcp_core.wifi_direct", "wifi_exec", "mdk4"),
    # recon
    "amass":             ("mcp_core.recon_direct", "recon_exec", "amass"),
    "subfinder":         ("mcp_core.recon_direct", "recon_exec", "subfinder"),
    "autorecon":         ("mcp_core.recon_direct", "recon_exec", "autorecon"),
    "theharvester":      ("mcp_core.recon_direct", "recon_exec", "theharvester"),
    "dnsenum":           ("mcp_core.recon_direct", "recon_exec", "dnsenum"),
    "fierce":            ("mcp_core.recon_direct", "recon_exec", "fierce"),
    "whois":             ("mcp_core.recon_direct", "recon_exec", "whois"),
    # net_scan
    "nmap":              ("mcp_core.net_scan_direct", "net_scan_exec", "nmap"),
    "nmap_advanced":     ("mcp_core.net_scan_direct", "net_scan_exec", "nmap-advanced"),
    "masscan":           ("mcp_core.net_scan_direct", "net_scan_exec", "masscan"),
    "rustscan":          ("mcp_core.net_scan_direct", "net_scan_exec", "rustscan"),
    "arp_scan":          ("mcp_core.net_scan_direct", "net_scan_exec", "arp-scan"),
    # web_scan
    "nikto":             ("mcp_core.web_scan_direct", "web_scan_exec", "nikto"),
    "sqlmap":            ("mcp_core.web_scan_direct", "web_scan_exec", "sqlmap"),
    "wpscan":            ("mcp_core.web_scan_direct", "web_scan_exec", "wpscan"),
    "dalfox":            ("mcp_core.web_scan_direct", "web_scan_exec", "dalfox"),
    "jaeles":            ("mcp_core.web_scan_direct", "web_scan_exec", "jaeles"),
    "xsser":             ("mcp_core.web_scan_direct", "web_scan_exec", "xsser"),
    "zap":               ("mcp_core.web_scan_direct", "web_scan_exec", "zap"),
    # web_fuzz
    "gobuster":          ("mcp_core.web_fuzz_direct", "web_fuzz_exec", "gobuster"),
    "ffuf":              ("mcp_core.web_fuzz_direct", "web_fuzz_exec", "ffuf"),
    "feroxbuster":       ("mcp_core.web_fuzz_direct", "web_fuzz_exec", "feroxbuster"),
    "dirsearch":         ("mcp_core.web_fuzz_direct", "web_fuzz_exec", "dirsearch"),
    "dirb":              ("mcp_core.web_fuzz_direct", "web_fuzz_exec", "dirb"),
    "wfuzz":             ("mcp_core.web_fuzz_direct", "web_fuzz_exec", "wfuzz"),
    "dotdotpwn":         ("mcp_core.web_fuzz_direct", "web_fuzz_exec", "dotdotpwn"),
    # password_cracking
    "hydra":             ("mcp_core.password_cracking_direct", "pwdcrack_exec", "hydra"),
    "hashcat":           ("mcp_core.password_cracking_direct", "pwdcrack_exec", "hashcat"),
    "john":              ("mcp_core.password_cracking_direct", "pwdcrack_exec", "john"),
    "medusa":            ("mcp_core.password_cracking_direct", "pwdcrack_exec", "medusa"),
    "patator":           ("mcp_core.password_cracking_direct", "pwdcrack_exec", "patator"),
    "hashid":            ("mcp_core.password_cracking_direct", "pwdcrack_exec", "hashid"),
    "ophcrack":          ("mcp_core.password_cracking_direct", "pwdcrack_exec", "ophcrack"),
    # smb_enum
    "enum4linux":        ("mcp_core.smb_enum_direct", "smb_enum_exec", "enum4linux"),
    "enum4linux-ng":     ("mcp_core.smb_enum_direct", "smb_enum_exec", "enum4linux-ng"),
    "netexec":           ("mcp_core.smb_enum_direct", "smb_enum_exec", "netexec"),
    "rpcclient":         ("mcp_core.smb_enum_direct", "smb_enum_exec", "rpcclient"),
    "smbmap":            ("mcp_core.smb_enum_direct", "smb_enum_exec", "smbmap"),
    "nbtscan":           ("mcp_core.smb_enum_direct", "smb_enum_exec", "nbtscan"),
    "nxc":               ("mcp_core.smb_enum_direct", "smb_enum_exec", "nxc"),
    "evil_winrm":        ("mcp_core.smb_enum_direct", "smb_enum_exec", "evil-winrm"),
    # exploit_framework
    "metasploit":        ("mcp_core.exploit_framework_direct", "exploit_exec", "metasploit"),
    "msfvenom":          ("mcp_core.exploit_framework_direct", "exploit_exec", "msfvenom"),
    "searchsploit":      ("mcp_core.exploit_framework_direct", "exploit_exec", "exploit_db"),
    "exploit_db":        ("mcp_core.exploit_framework_direct", "exploit_exec", "exploit_db"),
    "pwntools":          ("mcp_core.exploit_framework_direct", "exploit_exec", "pwntools"),
    # web_recon
    "katana":            ("mcp_core.web_recon_direct", "web_recon_exec", "katana"),
    "hakrawler":         ("mcp_core.web_recon_direct", "web_recon_exec", "hakrawler"),
    "gau":               ("mcp_core.web_recon_direct", "web_recon_exec", "gau"),
    "waybackurls":       ("mcp_core.web_recon_direct", "web_recon_exec", "waybackurls"),
    "httpx":             ("mcp_core.web_recon_direct", "web_recon_exec", "httpx"),
    "wafw00f":           ("mcp_core.web_recon_direct", "web_recon_exec", "wafw00f"),
    "arjun":             ("mcp_core.web_recon_direct", "web_recon_exec", "arjun"),
    "paramspider":       ("mcp_core.web_recon_direct", "web_recon_exec", "paramspider"),
    "x8":                ("mcp_core.web_recon_direct", "web_recon_exec", "x8"),
    # security
    "prowler":           ("mcp_core.security_direct", "security_exec", "prowler"),
    "trivy":             ("mcp_core.security_direct", "security_exec", "trivy"),
    "kube_hunter":       ("mcp_core.security_direct", "security_exec", "kube-hunter"),
    "kube_bench":        ("mcp_core.security_direct", "security_exec", "kube-bench"),
    "checkov":           ("mcp_core.security_direct", "security_exec", "checkov"),
    "terrascan":         ("mcp_core.security_direct", "security_exec", "terrascan"),
    # misc
    "ropgadget":         ("mcp_core.misc_direct", "misc_exec", "ropgadget"),
    "ropper":            ("mcp_core.misc_direct", "misc_exec", "ropper"),
    "one_gadget":        ("mcp_core.misc_direct", "misc_exec", "one_gadget"),
    "volatility":        ("mcp_core.misc_direct", "misc_exec", "volatility"),
    "volatility3":       ("mcp_core.misc_direct", "misc_exec", "volatility3"),
    "gdb":               ("mcp_core.misc_direct", "misc_exec", "gdb"),
    "radare2":           ("mcp_core.misc_direct", "misc_exec", "radare2"),
    "strings":           ("mcp_core.misc_direct", "misc_exec", "strings"),
    "objdump":           ("mcp_core.misc_direct", "misc_exec", "objdump"),
    "checksec":          ("mcp_core.misc_direct", "misc_exec", "checksec"),
    "binwalk":           ("mcp_core.misc_direct", "misc_exec", "binwalk"),
    "ghidra":            ("mcp_core.misc_direct", "misc_exec", "ghidra"),
    "angr":              ("mcp_core.misc_direct", "misc_exec", "angr"),
    "xxd":               ("mcp_core.misc_direct", "misc_exec", "xxd"),
    "mysql":             ("mcp_core.misc_direct", "misc_exec", "mysql"),
    "sqlite":            ("mcp_core.misc_direct", "misc_exec", "sqlite"),
    "exiftool":          ("mcp_core.misc_direct", "misc_exec", "exiftool"),
    "foremost":          ("mcp_core.misc_direct", "misc_exec", "foremost"),
    "steghide":          ("mcp_core.misc_direct", "misc_exec", "steghide"),
    "hashpump":          ("mcp_core.misc_direct", "misc_exec", "hashpump"),
    "anew":              ("mcp_core.misc_direct", "misc_exec", "anew"),
    "uro":               ("mcp_core.misc_direct", "misc_exec", "uro"),
    "nuclei":            ("mcp_core.misc_direct", "misc_exec", "nuclei"),
    "responder":         ("mcp_core.misc_direct", "misc_exec", "responder"),
    "jwt_analyzer":      ("mcp_core.misc_direct", "misc_exec", "jwt_analyzer"),
    "autopsy":           ("mcp_core.misc_direct", "misc_exec", "autopsy"),
    "libc":              ("mcp_core.misc_direct", "misc_exec", "libc"),
    "api_schema_analyzer": ("mcp_core.misc_direct", "misc_exec", "api_schema_analyzer"),
    "graphql_scanner":   ("mcp_core.misc_direct", "misc_exec", "graphql_scanner"),
    "api_fuzzer":        ("mcp_core.misc_direct", "misc_exec", "api_fuzzer"),
    "bbot":              ("mcp_core.misc_direct", "misc_exec", "bbot"),
    "bulk_extractor":    ("mcp_core.misc_direct", "misc_exec", "bulk_extractor"),
    "scalpel":           ("mcp_core.misc_direct", "misc_exec", "scalpel"),
    "falco":             ("mcp_core.misc_direct", "misc_exec", "falco"),
    "qsreplace":         ("mcp_core.misc_direct", "misc_exec", "qsreplace"),
    "http_request":      ("mcp_core.misc_direct", "misc_exec", "curl"),
    # web_probe
    "whatweb":           ("mcp_core.web_probe_direct", "web_probe_exec", "whatweb"),
    "commix":            ("mcp_core.web_probe_direct", "web_probe_exec", "commix"),
    "joomscan":          ("mcp_core.web_probe_direct", "web_probe_exec", "joomscan"),
    # testssl
    "testssl":           ("mcp_core.testssl_direct", "testssl_exec", "testssl"),
    # vuln_intel
    "vulnx":             ("mcp_core.vuln_intel_direct", "vuln_intel_exec", "vulnx"),
    # osint
    "sherlock":          ("mcp_core.osint_direct", "osint_exec", "sherlock"),
    "spiderfoot":        ("mcp_core.osint_direct", "osint_exec", "spiderfoot"),
    "sublist3r":         ("mcp_core.osint_direct", "osint_exec", "sublist3r"),
    "parsero":           ("mcp_core.osint_direct", "osint_exec", "parsero"),
    # active_directory
    "impacket":          ("mcp_core.active_directory_direct", "ad_exec", "impacket"),
    "ldapdomaindump":    ("mcp_core.active_directory_direct", "ad_exec", "ldapdomaindump"),
    "adidnsdump":        ("mcp_core.active_directory_direct", "ad_exec", "adidnsdump"),
    "certipy":           ("mcp_core.active_directory_direct", "ad_exec", "certipy_ad"),
    "certipy_ad":        ("mcp_core.active_directory_direct", "ad_exec", "certipy_ad"),
    "mitm6":             ("mcp_core.active_directory_direct", "ad_exec", "mitm6"),
    "pywerview":         ("mcp_core.active_directory_direct", "ad_exec", "pywerview"),
    "bloodhound":        ("mcp_core.active_directory_direct", "ad_exec", "bloodhound"),
    "bloodhound_python": ("mcp_core.active_directory_direct", "ad_exec", "bloodhound"),
    # aliases (not in hexstrike.py DIRECT_ROUTES, but present in server_setup DIRECT_TOOLS)
    "bettercap_wifi":    ("mcp_core.wifi_direct", "wifi_exec", "bettercap_wifi"),
    "wifite2":           ("mcp_core.wifi_direct", "wifi_exec", "wifite2"),
}
