name: Build & Publish Docker Image

on:
  push:
  pull_request:
  workflow_dispatch:


permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login GHCR
      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Convertir le nom du repo en lowercase (obligatoire pour GHCR)
      - name: Set lowercase repo slug
        run: |
          # use bash lowercase expansion so GITHUB_REPOSITORY is expanded and lowercased
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # 4. Build & Push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
